### ISSUE TITLE
Creates dummy titlebar in Firefox if there is no titlebar enabled.

### ISSUE THREAD

**Issue by CheeseEMan** [UbuntuBudgie/budgie-pixel-saver-applet#1]
You can set Firefox to run without a titlebar in the customize menu, however a dummy titlebar is created when using this applet. This does not occur with Chromium or other applications with client side decorations like GTK3 apps.
![Pixel-Saver-Issue](https://user-images.githubusercontent.com/43728665/59800691-453ef300-92b5-11e9-879b-dd6156d52196.png)

**Comment by fossfreedom** [comment]
its working just fine on ubuntu budgie 18.04 using the patches in this repo.

Are you using UB with the pixel saver package in our backports PPA?

**Comment by fossfreedom** [comment]
closing as there has been no response

**Comment by grahammtbr** [comment]
This issue still exists on 19.10. Pixel saver was installed through the welcome centre with backports enabled.

**Comment by fossfreedom** [comment]
Doubt that we can do anything here. Firefox is doing something very weird probably because it's not a native gtk3 app. If you can figure out a fix then happy to incorporate it.

**Comment by grahammtbr** [comment]
I'm not a programmer (outside of HTML/CSS and some PHP), so I can't be of any help there. Just thought I'd report it, as it may have an known issue (and/or fix) popping up again. I've lived this long without pixel saver, I'll make it a little longer ;)

**Comment by Coeur-Noir** [comment]
Maybe a kind of exclude list inside pixel saver applet, to exclude some app's from being taken care by it ?

But yes, pixel saver probably can't work with app's that don't build a complete title bar ( CSD or this kind of confusing hacks between title bar and menus ).

If you need pixel saver, you need app's with title bar and no CSD.

**Comment by fossfreedom** [comment]
Ok - I've added a gsettings key for the applet that allows for given apps to not work with pixel saver - such as firefox.

Think this resolves this but it does need testing to confirm.

**Comment by tonypuglieso** [comment]
Hello pixel saver its really good in general situations. Buts on windows no have native decoration, Pixel Saver generates a Dummy Tittle Bar, and buggy the apps. Its same  issue to #1

This is normal 
![Screenshot from 2021-03-09 12:09:45](https://user-images.githubusercontent.com/52177646/110494199-1fcdca80-80d2-11eb-8d72-6d85a612444a.png)

This is if Pixel Saver its on

![Screenshot from 2021-03-09 12:12:21](https://user-images.githubusercontent.com/52177646/110494190-1cd2da00-80d2-11eb-8655-823d19b591ea.png)

How i add these programs to ignore list?

**Comment by tonypuglieso** [comment]
> Ok - I've added a gsettings key for the applet that allows for given apps to not work with pixel saver - such as firefox.
> Think this resolves this but it does need testing to confirm.

This is from this source, or work on applet installed on (Budgie-Extras). Thanks.

Edit: if im trying to compile have the error.

---
Build started at 2021-03-09T12:59:26.894930
Main binary: /usr/bin/python3
Build Options: -Dprefix=/usr -Dbuildtype=plain
Python system: Linux
The Meson build system
Version: 0.53.2
Source dir: /home/tony/Downloads/budgie-pixel-saver-applet-3.0.1
Build dir: /home/tony/Downloads/budgie-pixel-saver-applet-3.0.1/build
Build type: native build
Project name: budgie_pixel_saver_applet
Project version: 2.0.0
No CFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc /home/tony/Downloads/budgie-pixel-saver-applet-3.0.1/build/meson-private/sanitycheckc.c -o /home/tony/Downloads/budgie-pixel-saver-applet-3.0.1/build/meson-private/sanitycheckc.exe -pipe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/tony/Downloads/budgie-pixel-saver-applet-3.0.1/build/meson-private/sanitycheckc.exe
C compiler for the build machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the build machine: cc ld.bfd 2.34

**meson.build:1:0: ERROR: Could not execute Vala compiler "valac"**
---

**Comment by Coeur-Noir** [comment]
> Ok - I've added a gsettings key for the applet that allows for given apps to not work with pixel saver

How test it ?
![dconf_pixel-saver](https://user-images.githubusercontent.com/1895947/110525038-6cd29080-8114-11eb-8571-2903222f1e17.png)

**Comment by tonypuglieso** [comment]
![image](https://user-images.githubusercontent.com/52177646/110539818-7b18b080-8104-11eb-9768-527bc80ec679.png)
Im search and "budgie-pixel-saver" dont apprear.

Now i have the applet installed from "budgie extras".

Do i need to compile this source and install?

**Comment by fossfreedom** [comment]
ok - git repo will need to be compiled and installed for your linux distro.

I've tweaked the schema just now - so the blacklist apps can be found in
dconf-editor in the net.milgar.budgie-pixel-saver blacklist-apps key

Blacklisted apps are the WM_CLASS name of the app - this can be found via

xprop | grep WM_CLASS

click on the app once you see the cross-hair

**Comment by fossfreedom** [comment]
Let me know which version of UB you are on - first one to respond gets to test a PPA that I will prepare just for you.

**Comment by tonypuglieso** [comment]
Hello thanks for your help. Im installed most of dependencies. Con compilation now the error its Run-time  dependencie "budgie-1.0"

```
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency gtk+-3.0 found: YES 3.24.20
Run-time dependency gdk-x11-3.0 found: YES 3.24.20
Run-time dependency glib-2.0 found: YES 2.64.6
Run-time dependency libpeas-1.0 found: YES 1.26.0
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency budgie-1.0 found: NO (tried pkgconfig and cmake)

meson.build:37:0: ERROR: Dependency "budgie-1.0" not found, tried pkgconfig and cmake
```

**Comment by fossfreedom** [comment]
if you have the backports PPA enabled - then in software-properties-gtk enable the source code repo for backports.

Run:

    sudo apt  build-dep budgie-pixel-saver-applet

This will install all the build dependencies for the applet.

budgie-1.0 is actually the budgie-core-dev package

**Comment by tonypuglieso** [comment]
Hello now my ubuntu budgie its 20.04 LTS.

Im compile good (Thanks you for this). 

> sudo ninja install
> [sudo] password for tony: 
> [0/1] Installing files.
> Installing src/BudgiePixelSaverApplet.plugin to /usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/budgie-pixel-saver-applet
> Installing src/libbudgiepixelsaverapplet.so to /usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/budgie-pixel-saver-applet
> Installing /mnt/Budgie/Software/Git/budgie-pixel-saver-applet/src/net.milgar.budgie-pixel-saver.gschema.xml to /usr/share/glib-2.0/schemas
> Installing /mnt/Budgie/Software/Git/budgie-pixel-saver-applet/src/net.milgar.budgie-pixel-saver.blacklist.gschema.xml to /usr/share/glib-2.0/schemas
> Running custom install script '/usr/bin/python3 /mnt/Budgie/Software/Git/budgie-pixel-saver-applet/meson_post_install.py'
> Compiling gsettings schemas...

And in dconf-editor now appears budguie-pixel-saver/blacklist-apps

![Screenshot from 2021-03-11 12:03:04](https://user-images.githubusercontent.com/52177646/110807485-dd3af800-8261-11eb-9569-e879f37caf37.png)

But the applet no appears on Budgie Desktop Settings (Im uninstall pixel-saver from Budgie-Extras>reboot; and now Ninja Install>reboot)

![Screenshot from 2021-03-11 12-06-33](https://user-images.githubusercontent.com/52177646/110807939-4c185100-8262-11eb-857a-7d0b00c2823a.png)

**Comment by fossfreedom** [comment]
compile with

    meson --prefix=/usr --libdir=/usr/lib
    ninja
    sudo ninja install

That will install the plugins etc to /usr/lib/budgie-desktop/plugins/....

Remember to restart the panel / logout and login for the applet to appear

    budgie-panel --replace &!

**Comment by tonypuglieso** [comment]
Hello now!

Can compile good, the applet appears on the "Budgie Desktop Settings" and work.
 
**What Work:**
>  **'TelegramDesktop'** now work fine. (I suposse a native linux program instaled from .deb)

**What don't Work:**

>  **'PureRef'** no work, but don't have glitches and can be work normal. (Its a Appimagen).
> **'Wine', 'dragonbonespro.exe', 'leagueclient.exe', 'leagueclientux.exe'** (Thats are Windows Apps on Wine).

I assume the Appimagen o WineApps are other problems.

![Screenshot from 2021-03-11 13:15:09](https://user-images.githubusercontent.com/52177646/110828317-ad95eb00-8275-11eb-85b1-a2f89a323d2b.png)

 
![Screenshot from 2021-03-11 14:27:32wwww](https://user-images.githubusercontent.com/52177646/110829010-6b20de00-8276-11eb-896d-215394ee99a7.jpg)

**Comment by fossfreedom** [comment]
Use xprop

Click the app. Look on the terminal for the WM_Class value.  That is the
string you use in the blacklist

**Comment by fossfreedom** [comment]
ok - this is been hanging around for too long.

I'm going to assume this issue is resolved.  I'll push an update of pixel-saver with these changes in the next day or so for 20.04 and later.

**Comment by tonypuglieso** [comment]
Hello sorry for no respond, i cant resolve this. Now i create a clean budgie 20.04 VMWare Machine
The process:

****Compilation Budgie-Pixel-Saver**
Active Ubuntu Budgie Backports:**
```
sudo add-apt-repository ppa:ubuntubudgie/backports
sudo apt-get update
```
**Install Dependencies**
```
sudo apt  build-dep budgie-pixel-saver-applet
```
**Download Git & Compile:**
```
git clone https://github.com/UbuntuBudgie/budgie-pixel-saver-applet
cd /budgie-pixel-saver-applet
mkdir build && cd build
meson --prefix=/usr --libdir=/usr/lib
ninja
sudo ninja install
```
```
sudo apt install dconf
sudo dconf update
sudo dconf-editor
budgie-panel --replace &!
```
**logout & login**

/net/milgar/budguie-pixel-saver/backlist-apps
Add WM_CLASS:
`xprop | grep WM_CLASS`

Download PureRef Appimage from https://www.pureref.com/download.php
xprop | grep WM_CLASS
WM_CLASS(STRING) = "PureRef-1.11.1_x64.Appimage", "PureRef"

![image](https://user-images.githubusercontent.com/52177646/113051916-e93d1a00-917c-11eb-95d0-1a22ff851e8f.png)

**Comment by fossfreedom** [comment]
Did you remember to logout and login after updating dconf?

How do you install "PureRef" ?  Its not something I'm aware of.

**Comment by tonypuglieso** [comment]
Yes, i log and login after updating dconf. and reboot too.

PureRef Downloar its free its u take 0$ price. Its a .appimage (take the file executable) or de .deb install a .appimage too. I test PureRef for simple.

Could it be possible that the problem is due to being an .appimage (a portable file)?
I have the same problems for Wine Emulated Programs/Games (Like Leage of Legends, Steam Client, Dragon Bones 2D program, etc).

But I have noticed that the changes that I make in dconf do not work properly. That is, if I add or remove Telegram for example, nothing happens, the changes are not updated I suppose.

**Comment by tonypuglieso** [comment]
> Yes, i log and login after updating dconf. and reboot too.
> 
> PureRef Downloar its free its u take 0$ price. Its a .appimage (take the file executable) or de .deb install a .appimage too. I test PureRef for simple.
> 
> Could it be possible that the problem is due to being an .appimage (a portable file)?
> I have the same problems for Wine Emulated Programs/Games (Like Leage of Legends, Steam Client, Dragon Bones 2D program, etc).
> 
> But I have noticed that the changes that I make in dconf do not work properly. That is, if I add or remove Telegram for example, nothing happens, the changes are not updated I suppose.




Hello now! Great thanks for your work, help and patience!

Edit: I really don't know why I didn't walk before. Now I could make it work both in the virtual machine and in the main computer
Edit2: **The Problem i Have are the dconf-editor no update after install pixel-saver.-**
Need to update dconf-editor & Edit Now
`sudo dconf update`

Now all work perfect. Dconf no need to logout & log in to work. If i change the blacklist need to restar the app to changes turn on.

Work perfect ignore: ['Firefox', 'TelegramDesktop', 'riotclientux.exe', 'dragonbonespro.exe', 'Wine', 'leagueclientux.exe', 'PureRef']

![Screenshot from 2021-03-31 13:53:48 For Github](https://user-images.githubusercontent.com/52177646/113183998-0fb98e80-922b-11eb-959b-ba7a31a19df2.png)
