### ISSUE TITLE
Zombie xprop processes leaking

### ISSUE THREAD

**Issue by elusian** [UbuntuBudgie/budgie-pixel-saver-applet#3]
I recently noticed that when reducing an application to icon an `xprop` process is created and never closed. This leads to a lot of zombie processes.

Since this didn't use to happen in the previous version (the one this was forked from to fix the applet for mutter > 3.32) I suspect that the issue is inside TitleBarManager::change_titlebar.

I'm on Solus, so I'm not sure this is the right place to report the issue...

**Comment by fossfreedom** [comment]
Hmm... thanks for the report.  Guess need to look where xprop is being used in the code.

**Comment by fossfreedom** [comment]
The above commit should resolve this - shout if it doesn't or causes other issues.
