### ISSUE TITLE
Metacity icons are showing unfocused one

### ISSUE THREAD

**Issue by MuhmmadZohaibImtiaz** [UbuntuBudgie/budgie-pixel-saver-applet#4]
I applied this theme [WhiteSur](https://www.gnome-look.org/p/1403328/#files-panel) and when i maximize with the pixel saver the metacity icons are shown of unfocused window even when the window is in focus.
This problem is not with Ant theme. So particularly, how can I fix this issue. 

![Budgie pixel saver 1](https://user-images.githubusercontent.com/71523302/95964510-4ee15800-0e22-11eb-91da-fb1fc7bd9f74.png)
![Budguie Pixel Saver 2](https://user-images.githubusercontent.com/71523302/95964531-54d73900-0e22-11eb-93bd-5dac0956b09d.png)

**Comment by fossfreedom** [comment]
does this occur with other themes such as pocillo, arc-theme, qogir?

**Comment by MuhmmadZohaibImtiaz** [comment]
No. suggested themes doesn't show this issue. All 3rd party themes show this issue/behavior.
If I can understand how it works maybe I can do a workaround.

**Comment by fossfreedom** [comment]
in pocillo pixel saver has sass code like this https://github.com/UbuntuBudgie/pocillo-gtk-theme/blob/93c61557db621122aa33c05ee18bec6eb0b22e28/src/gtk-3.0/3.22/sass/apps/_budgie.scss#L175

You'll need to either contribute a fix to white-sur theme to add similar theme fixes or develop an override in .config/gtk-3.0/gtk.css - probably to override/disable the not active  metacity icon CSS

**Comment by MuhmmadZohaibImtiaz** [comment]
@fossfreedom can you tell any document for budgie theme development. So, I can understand the scope of each property and its accessibility in scss file.

**Comment by fossfreedom** [comment]
I'm not aware of such a document.

In general for GTK based apps I would use the GTK Inspector to interrogate
and look a the CSS in use.

So for the panel

    GTK_DEBUG=interactive budgie-panel --replace

Then you can drill down to the pixel-saver applet and look at the CSS
properties.  You can also try out CSS changes as well.

**Comment by MuhmmadZohaibImtiaz** [comment]
Issue has been resolved by WhiteSur theme author Vince
