### ISSUE TITLE
Doesn't use system theme for buttons

### ISSUE THREAD

**Issue by NovaViper** [UbuntuBudgie/budgie-pixel-saver-applet#5]
Hi, im using EndeavourOS 3.5.1 with Budgie and I notice that this applet doesn't use the global theme (which is Layan). I installed the applet from the [AUR](https://aur.archlinux.org/packages/budgie-pixel-saver-applet-ubuntubudgie-git/)

**Comment by fossfreedom** [comment]
What's the theme option you used for the applet?

**Comment by NovaViper** [comment]
@fossfreedom I have the theme styling option enabled for the applet

**Comment by NovaViper** [comment]
Huh, I just noticed that the applet seems to be pulling from the icon themes instead of the global themes

**Comment by NovaViper** [comment]
I also noticed that even when I turn off use theme styling, it still changes whenever I select the global icons theme (but not for the widgets/window decoration theme)

**Comment by NovaViper** [comment]
@fossfreedom Hey uh, I just downloaded the latest commit to see if it works but the issue is still present, it still not using the window decorations, but is using the icon theme setting instead, as shown in the screenshot. Is that intended behavior?

![Screenshot from 2020-10-25 22-33-22](https://user-images.githubusercontent.com/7191115/97131563-75509e80-1712-11eb-88d1-dbcdbbd2b4dc.png)

![Screenshot from 2020-10-25 22-36-56](https://user-images.githubusercontent.com/7191115/97131657-b6e14980-1712-11eb-81fc-335a1edeb4c0.png)

**Comment by fossfreedom** [comment]
Works just fine for me using pocillo icons and tested with arc, pocillo and
qogir themes.

Any other themes and icons we cannot support

**Comment by NovaViper** [comment]
It only switches when I change the icon theme, but not the global theme. Is that intended? As when I change the global theme (not the icons theme), it doesn't change for any of the themes available (stock and otherwise), but when I only switch the icon theme the buttons change (but they don't take on the full styling of the window decorations)

**Comment by fossfreedom** [comment]
I have no idea what the original author intended here.

Your icon theme needs to support the window button icon names as described
in that commit code module.

**Comment by NovaViper** [comment]
Hm.. I feel like the original intention was suppose to have the window buttons match those of what the window decorations (which are in the global theme, not in the icon themes).

Like this theme changes the window decorations.
![image](https://user-images.githubusercontent.com/7191115/97241960-8eb02400-17c0-11eb-8511-4341280e36cd.png)

However the main issue with the current commit is that it's specifically looking at the icons theme, but not the global theme (where the window decoration assets are located and this is for every single theme, including the ones included with the DE)
