### ISSUE TITLE
Theming of window controls needs a revisit

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-pixel-saver-applet#8]
It is kind of hit and miss at the moment.

This thread covers the issues that need to be looked at.

https://discourse.ubuntubudgie.org/t/adapta-and-pixel-saver-applet/661/19

**Comment by AkiraMiyakoda** [comment]
I have located the cause of this issue.
This is because some themes like **Vimix** expect the window control buttons to be contained by ```HeaderBar```.

 I'm now thinking how to implement it...
